### ISSUE TITLE
Lumen error (Debugbar v3.6.2)

### ISSUE THREAD

**Issue by coolycow** [barryvdh/laravel-debugbar#1200]
Hi!

After updating the package, the following error appeared:
```
local.ERROR: Barryvdh\Debugbar\ServiceProvider::Barryvdh\Debugbar\{closure}(): Argument #2 ($application) must be of type Illuminate\Foundation\Application, Laravel\Lumen\Application given, called in /var/www/myproject/vendor/illuminate/container/Container.php on line 763 {"exception":"[object] (TypeError(code: 0): Barryvdh\\Debugbar\\ServiceProvider::Barryvdh\\Debugbar\\{closure}(): Argument #2 ($application) must be of type Illuminate\\Foundation\\Application, Laravel\\Lumen\\Application given, called in /var/www/myproject/vendor/illuminate/container/Container.php on line 763 at /var/www/myproject/vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php:59)
[stacktrace]
#0 /var/www/myproject/vendor/illuminate/container/Container.php(763): Barryvdh\\Debugbar\\ServiceProvider->Barryvdh\\Debugbar\\{closure}()
#1 /var/www/myproject/vendor/illuminate/container/Container.php(692): Illuminate\\Container\\Container->resolve()
#2 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#3 /var/www/myproject/vendor/illuminate/container/Container.php(1418): Laravel\\Lumen\\Application->make()
#4 /var/www/myproject/vendor/illuminate/view/ViewServiceProvider.php(38): Illuminate\\Container\\Container->offsetGet()
#5 /var/www/myproject/vendor/illuminate/container/Container.php(869): Illuminate\\View\\ViewServiceProvider->Illuminate\\View\\{closure}()
#6 /var/www/myproject/vendor/illuminate/container/Container.php(754): Illuminate\\Container\\Container->build()
#7 /var/www/myproject/vendor/illuminate/container/Container.php(692): Illuminate\\Container\\Container->resolve()
#8 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#9 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(668): Laravel\\Lumen\\Application->make()
#10 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(648): Laravel\\Lumen\\Application->loadComponent()
#11 /var/www/myproject/vendor/illuminate/container/Container.php(869): Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}()
#12 /var/www/myproject/vendor/illuminate/container/Container.php(754): Illuminate\\Container\\Container->build()
#13 /var/www/myproject/vendor/illuminate/container/Container.php(692): Illuminate\\Container\\Container->resolve()
#14 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#15 /var/www/myproject/vendor/illuminate/container/Container.php(1418): Laravel\\Lumen\\Application->make()
#16 /var/www/myproject/vendor/illuminate/mail/MailManager.php(118): Illuminate\\Container\\Container->offsetGet()
#17 /var/www/myproject/vendor/illuminate/mail/MailManager.php(94): Illuminate\\Mail\\MailManager->resolve()
#18 /var/www/myproject/vendor/illuminate/mail/MailManager.php(72): Illuminate\\Mail\\MailManager->get()
#19 /var/www/myproject/vendor/illuminate/mail/MailServiceProvider.php(33): Illuminate\\Mail\\MailManager->mailer()
#20 /var/www/myproject/vendor/illuminate/container/Container.php(869): Illuminate\\Mail\\MailServiceProvider->Illuminate\\Mail\\{closure}()
#21 /var/www/myproject/vendor/illuminate/container/Container.php(754): Illuminate\\Container\\Container->build()
#22 /var/www/myproject/vendor/illuminate/container/Container.php(692): Illuminate\\Container\\Container->resolve()
#23 /var/www/myproject/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#24 /var/www/myproject/vendor/illuminate/container/Container.php(1418): Laravel\\Lumen\\Application->make()
#25 /var/www/myproject/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(455): Illuminate\\Container\\Container->offsetGet()
#26 /var/www/myproject/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(63): Barryvdh\\Debugbar\\LaravelDebugbar->boot()
#27 /var/www/myproject/vendor/illuminate/pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#28 /var/www/myproject/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/myproject/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}()
#30 /var/www/myproject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then()
#31 /var/www/myproject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline()
#32 /var/www/myproject/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\\Lumen\\Application->dispatch()
#33 /var/www/myproject/public/index.php(28): Laravel\\Lumen\\Application->run()
#34 {main}
"} 
```

Version 3.5 works correctly.

**Comment by sashsvamir** [comment]
To works debugbar in lumen and fix this issue, i'm suggest to use `\Illuminate\Container\Container` that extends both `Laravel` and `Lumen` Application in extend function.

**Comment by pataar** [comment]
Bumping this to prevent it from becoming closed
