### ISSUE TITLE
Argument #1 ($string) must be of type string, Illuminate\Database\Events\QueryExecuted given

### ISSUE THREAD

**Issue by wimski** [barryvdh/laravel-debugbar#1530]
PHP 8.3.2
`laravel/framework`: 10.44.0
`barryvdh/laravel-debugbar`: 3.10.3

```
[xx-xx-xx xx:xx:xx] local.ERROR: mb_strwidth(): Argument #1 ($string) must be of type string, Illuminate\Database\Events\QueryExecuted given {"exception":"[object] (TypeError(code: 0): mb_strwidth(): Argument #1 ($string) must be of type string, Illuminate\\Database\\Events\\QueryExecuted given at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php:596)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php(596): mb_strwidth(Object(Illuminate\\Database\\Events\\QueryExecuted), 'UTF-8')
#1 /var/www/html/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php(228): Illuminate\\Support\\Str::limit(Object(Illuminate\\Database\\Events\\QueryExecuted), 100)
#2 /var/www/html/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(382): Barryvdh\\Debugbar\\DataCollector\\QueryCollector->addQuery(Object(Illuminate\\Database\\Events\\QueryExecuted))
```

```php
// Barryvdh\Debugbar\DataCollector\QueryCollector

    /**
     *
     * @param \Illuminate\Database\Events\QueryExecuted $query
     */
    public function addQuery($query)
    {
        // ...

        if ($this->timeCollector !== null) {
            $this->timeCollector->addMeasure(Str::limit($query, 100), $startTime, $endTime, [], 'db'); // line:228
        }
    }
```

```php
// Illuminate\Support\Str

    /**
     * Limit the number of characters in a string.
     *
     * @param  string  $value
     * @param  int  $limit
     * @param  string  $end
     * @return string
     */
    public static function limit($value, $limit = 100, $end = '...')
    {
        if (mb_strwidth($value, 'UTF-8') <= $limit) { // line: 596
            return $value;
        }

        return rtrim(mb_strimwidth($value, 0, $limit, '', 'UTF-8')).$end;
    }
```

**Comment by wimski** [comment]
Ah, this seems to be fixed just yesterday :see_no_evil:
* https://github.com/barryvdh/laravel-debugbar/pull/1524
* https://github.com/barryvdh/laravel-debugbar/releases/tag/v3.10.4
