### ISSUE TITLE
Require(debugbar) fails

### ISSUE THREAD

**Issue by AnthonyPorthouse** [barryvdh/laravel-debugbar#268]
When deploying my L5 application via Forge, I get the following error when it tries to generate the autoload files.

`PHP Warning:  Uncaught exception 'ErrorException' with message 'require(debugbar): failed to open stream: No such file or directory' in /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:57`

**Comment by barryvdh** [comment]
Are you on the latest laravel 5.0 version and laraveldebugbar 2.0 version?

**Comment by AnthonyPorthouse** [comment]
Yes, the snippet from the relevant section of my composer.json file is below
```
	"require": {
		"laravel/framework": "~5.0",
		"barryvdh/laravel-debugbar": "~2.0@dev"
	},
```

**Comment by barryvdh** [comment]
Did you `composer update` today/yesterday?

**Comment by AnthonyPorthouse** [comment]
Yesterday, just before I placed the issue and that didn't change anything.

**Comment by barryvdh** [comment]
Perhaps clear your compiled files manually?

**Comment by AnthonyPorthouse** [comment]
Tried that, upon running `composer install` again I received the same error.

```
Script php artisan clear-compiled handling the post-install-cmd event returned with an error


                                                                                                                       
  [RuntimeException]                                                                                                   
  Error Output: PHP Warning:  Uncaught exception 'ErrorException' with message 'require(debugbar): failed to open str  
  eam: No such file or directory' in /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/ServiceProvi  
  der.php:57                                                                                                           
  Stack trace:                                                                                                         
  #0 /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(57): Illuminate\Foundati  
  on\Bootstrap\HandleExceptions->handleError(2, 'require(debugba...', '/home/forge/def...', 57, Array)                 
  #1 /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(57): Illuminate\Support\  
  ServiceProvider->mergeConfigFrom()                                                                                   
  #2 /home/forge/default/vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php(73): Illuminate\Support\ServiceProv  
  ider->mergeConfigFrom('/home/forge/def...', 'debugbar')                                                              
  #3 /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(415): Barryvdh\Debugbar\S  
  erviceProvider->register()                                                                                           
  #4 /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Fo  
  unda in /home/forge/default/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 57           
  PHP Stack trace:                                                                                                     
  PHP   1. {main}() /home/forge/default/artisan:0                                                                      
  PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/forge/default/artisan:34                               
  PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/forge/default/vendor/laravel/framework/src/Illumin  
  ate/Foundation/Console/Kernel.php:89                                                                                 
  PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/forge/default/vendor/laravel/framework/src/Illumi  
  nate/Foundation/Console/Kernel.php:180                                                                               
  PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/forge/default/vendor/laravel/framewor  
  k/src/Illuminate/Foundation/Application.php:158                                                                      
  PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/forge/default/vendor/laravel/framew  
  ork/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:15                                                     
  PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/forge/default/vendor/laravel/framework/src/Illumina  
  te/Foundation/Application.php:391                                                                                    
  PHP   8. Illuminate\Foundation\Application->register() /home/forge/default/vendor/laravel/framework/src/Illuminate/  
  Foundation/ProviderRepository.php:75                                                                                 
  PHP   9. Barryvdh\Debugbar\ServiceProvider->register() /home/forge/default/vendor/laravel/framework/src/Illuminate/  
  Foundation/Application.php:415                                                                                       
  PHP  10. Illuminate\Support\ServiceProvider->mergeConfigFrom() /home/forge/default/vendor/barryvdh/laravel-debugbar  
  /src/ServiceProvider.php:73                                                                                          
  PHP Fatal error:  Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required 'debugbar' (includ  
  e_path='/home/forge/default/vendor/phpunit/php-text-template:/home/forge/default/vendor/phpunit/php-file-iterator:/  
  home/forge/default/vendor/phpunit/php-timer:.:/usr/share/php:/usr/share/pear') in /home/forge/default/vendor/larave  
  l/framework/src/Illuminate/Support/ServiceProvider.php on line 57                                                    
  PHP Stack trace:                                                                                                     
  PHP   1. {main}() /home/forge/default/artisan:0                                                                      
  PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/forge/default/artisan:34                               
  PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/forge/default/vendor/laravel/framework/src/Illumin  
  ate/Foundation/Console/Kernel.php:89                                                                                 
  PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/forge/default/vendor/laravel/framework/src/Illumi  
  nate/Foundation/Console/Kernel.php:180                                                                               
  PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/forge/default/vendor/laravel/framewor  
  k/src/Illuminate/Foundation/Application.php:158                                                                      
  PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/forge/default/vendor/laravel/framew  
  ork/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:15                                                     
  PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/forge/default/vendor/laravel/framework/src/Illumina  
  te/Foundation/Application.php:391                                                                                    
  PHP   8. Illuminate\Foundation\Application->register() /home/forge/default/vendor/laravel/framework/src/Illuminate/  
  Foundation/ProviderRepository.php:75                                                                                 
  PHP   9. Barryvdh\Debugbar\ServiceProvider->register() /home/forge/default/vendor/laravel/framework/src/Illuminate/  
  Foundation/Application.php:415                                                                                       
  PHP  10. Illuminate\Support\ServiceProvider->mergeConfigFrom() /home/forge/default/vendor/barryvdh/laravel-debugbar  
  /src/ServiceProvider.php:73
```

**Comment by barryvdh** [comment]
Sorry I still think your laravel 5 version is probably out of date. Not sure what to do.
Perhaps delete the vendor folder entirely and re-install all vendors or something.

**Comment by AnthonyPorthouse** [comment]
That seems to have sorted it. Thanks.
