### ISSUE TITLE
Argument 2 passed to Barryvdh\Debugbar\LaravelDebugbar::modifyResponse() 

### ISSUE THREAD

**Issue by MrTomek** [barryvdh/laravel-debugbar#913]
Hello, I have a problem and I do not know how to deal with it.

```
[2019-02-28 17:10:43] local.ERROR: Argument 2 passed to Barryvdh\Debugbar\LaravelDebugbar::modifyResponse() must be an instance of Symfony\Component\HttpFoundation\Response, null given, called in /home/mrtomek/git/multisite-generator/htdocs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php on line 74 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 2 passed to Barryvdh\\Debugbar\\LaravelDebugbar::modifyResponse() must be an instance of Symfony\\Component\\HttpFoundation\\Response, null given, called in /home/mrtomek/git/multisite-generator/htdocs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php on line 74 at /home/mrtomek/git/multisite-generator/htdocs/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:618)
[stacktrace]
#0 /home/mrtomek/git/multisite-generator/htdocs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(74): Barryvdh\\Debugbar\\LaravelDebugbar->modifyResponse(Object(Illuminate\\Http\\Request), NULL)
#1 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#2 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#3 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#4 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#5 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#6 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#8 /home/mrtomek/git/multisite-generator/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#9 /home/mrtomek/git/multisite-generator/htdocs/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#10 {main}
"} 
```

**Comment by laurenwilliams92** [comment]
I am also having the same issue. Did you manage to solve it?

**Comment by Yuriy-Svetlov** [comment]
I have the same issue.

**Comment by Yuriy-Svetlov** [comment]
This happens to me if I call a view or call a view with parameters

This code throws this error
```
    public function home(){
        $trans = new Translator('home');
       
        return view('home', [
            'trans' => $trans,
            'transNav' => $this->transNav,
        ]);
    }
```
